- hosts: master
  become: yes
  tasks:
    - name: initialize the cluster
      shell: kubeadm init --pod-network-cidr=10.244.0.0/16 
      args:
        chdir: $HOME

    - name: create .kube directory
      become: yes
      become_user: niharika
      file:
        path: $HOME/.kube
        state: directory
        mode: 0755

    - name: copy admin.conf to user's kube config
      copy:
        src: /etc/kubernetes/admin.conf
        dest: /home/niharika/.kube/config
        remote_src: yes
        owner: niharika

    - name: execute cmd
      become: yes
      become_user: niharika
      shell: chown $(id -u):$(id -g) $HOME/.kube/config
      args:
        chdir: $HOME

    - name: install Pod network
      become: yes
      become_user: niharika
      shell: kubectl apply -f https://raw.githubusercontent.com/coreos/flannel/a70459be0084506e4ec919aa1c114638878db11b/Documentation/kube-flannel.yml >> pod_network_setup.txt
      args:
        chdir: $HOME
        creates: pod_network_setup.txt
